### PR TITLE
Adopt the latest Pulumi codegen version

### PR DESCRIPTION
**Pull request by joeduffy**

### CODE REVIEW

**Comment by joeduffy** [comment]
The build seems to be failing (a Python error about `ResourceOptions` missing? all the downstream tests fail?) These don't appear related to this change, however, it's sufficiently bad looking that I don't want to just merge this. I was able to unblock myself anyhow by just manually bumping the `pulumi/pulumi` version in my Lambda with `go get ...`.

@pgavlin thoughts on the build failures and whether you want to take this change?

**Comment by stack72** [comment]
@joeduffy I pinged in slack what the issue was - they pulled the 3.6.10 python release :/ so if you bump the GHA template to reference 3.6.11 then the build will give a real diff

**Comment by stack72** [comment]
What one of the issues is ;)

**Comment by komalali** [comment]
Closing out of date PR

**Pull request closed without merging**
