### PR TITLE
Upgrade to Go 1.14.x

### PR DESCRIPTION
**Pull request by stack72**

### CODE REVIEW

**Comment by pgavlin** [comment]
Release notes look clean. :shipit:

**Comment by stack72** [comment]
@pgavlin theres a broken test - not sure if this is related to the upgrade or not - thoughts on it?

**Comment by pgavlin** [comment]
Looks like an intermittent failure.

**Comment by stack72** [comment]
Ok will proceed with merge and fix in master if it appears again

**Pull request merged**
