### PR TITLE
Upgrade dependencies.

### PR DESCRIPTION
**Pull request by pgavlin**
Notabluy:
- terraform -> terraform v0.12.9
- pulumi-terraform -> pulumi-terraform-bridge

The first change required that we vendor in the TF11 module loader and
config package, as the new version of TF12 has removed that code.

The second change required that we link in a very slightly modified
version of terraform-provider-sdk, as that package registers types with
gob that conflict with types registered by terraform itself.

With these changes, we now have a setup that will allow us to update
tf2pulumi to understand both TF11 and TF12 config in the same binary.

### CODE REVIEW

**Comment by pgavlin** [comment]
The vast majority of the changes in this PR are related to vendoring in the TF11 module loader.

**Comment by CyrusNajmabadi** [comment]
>The vast majority of the changes in this PR are related to vendoring in the TF11 module loader.

1. Is that the 'internal' directory?  
2. Are there copyright/attestation concerns?
3. Are there specific areas you want me to focus on?

**Comment by CyrusNajmabadi** [comment]
image

=-o   

What should  look at in this to make this more manageable.

**Comment by pgavlin** [comment]
> Is that the 'internal' directory?

Yes.

> Are there copyright/attestation concerns?

Yes--I added a `README.md` and a `LICENSE` to `internal/config` to address these.

> Are there specific areas you want me to focus on?

Not particularly. You can ignore the changes to the `internal` directory, though.

**Comment by CyrusNajmabadi** [comment]
Great, thanks.  Will review the rest tonight/tomorrow.

**Pull request merged**
